# Generated by Django 5.0.1 on 2024-01-28 19:06

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategoriler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(max_length=255, verbose_name="sayfa")),
                (
                    "page_tr",
                    models.CharField(max_length=255, null=True, verbose_name="sayfa"),
                ),
                (
                    "page_en",
                    models.CharField(max_length=255, null=True, verbose_name="sayfa"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("title", models.CharField(max_length=255)),
                ("title_tr", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("keywords", models.CharField(max_length=255)),
                ("keywords_tr", models.CharField(max_length=255, null=True)),
                ("keywords_en", models.CharField(max_length=255, null=True)),
                ("description", models.CharField(max_length=255)),
                ("description_tr", models.CharField(max_length=255, null=True)),
                ("description_en", models.CharField(max_length=255, null=True)),
                ("phone_fixed", models.CharField(max_length=15)),
                ("phone_mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("facebook_url", models.URLField(max_length=250)),
                ("instagram_url", models.URLField(max_length=250)),
                ("linkedin_url", models.URLField(max_length=250)),
                ("twitter_url", models.URLField(max_length=250)),
                ("youtube_url", models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Postlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlık")),
                (
                    "title_tr",
                    models.CharField(max_length=255, null=True, verbose_name="Başlık"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=255, null=True, verbose_name="Başlık"),
                ),
                ("contents", tinymce.models.HTMLField(verbose_name="İçerik")),
                (
                    "contents_tr",
                    tinymce.models.HTMLField(null=True, verbose_name="İçerik"),
                ),
                (
                    "contents_en",
                    tinymce.models.HTMLField(null=True, verbose_name="İçerik"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/",
                        verbose_name="Fotoğraf",
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yayınlanma Tarihi"
                    ),
                ),
                (
                    "release_date_tr",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Yayınlanma Tarihi"
                    ),
                ),
                (
                    "release_date_en",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Yayınlanma Tarihi"
                    ),
                ),
                (
                    "pages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcore.kategoriler",
                    ),
                ),
                (
                    "pages_en",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcore.kategoriler",
                    ),
                ),
                (
                    "pages_tr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcore.kategoriler",
                    ),
                ),
            ],
        ),
    ]
