# Generated by Django 5.0.1 on 2024-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tcore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriler",
            name="page",
            field=models.CharField(max_length=255, verbose_name="Sayfa"),
        ),
        migrations.AlterField(
            model_name="kategoriler",
            name="page_en",
            field=models.CharField(max_length=255, null=True, verbose_name="Sayfa"),
        ),
        migrations.AlterField(
            model_name="kategoriler",
            name="page_tr",
            field=models.CharField(max_length=255, null=True, verbose_name="Sayfa"),
        ),
    ]
