# Generated by Django 5.0.1 on 2024-01-28 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tcore", "0002_alter_kategoriler_page_alter_kategoriler_page_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postlar",
            old_name="pages",
            new_name="page",
        ),
        migrations.RenameField(
            model_name="postlar",
            old_name="pages_en",
            new_name="page_en",
        ),
        migrations.RenameField(
            model_name="postlar",
            old_name="pages_tr",
            new_name="page_tr",
        ),
    ]
